### ISSUE TITLE
XeLaTeX: There is no (U+0020) in font SimpleIcons Filtered

### ISSUE THREAD

**Issue by Rimole** [ineshbose/simple-icons-latex#18]
```
\documentclass{article}
\usepackage{simpleicons}
\begin{document}
\end{document}
```

compiled with XeLaTeX gives:

Missing character: There is no   (U+0020) in font SimpleIcons Filtered!
Missing character: There is no   (U+0020) in font SimpleIcons Filtered/OT!
Missing character: There is no   (U+0020) in font SimpleIcons Filtered/OT:language=dflt;!
Missing character: There is no   (U+0020) in font SimpleIcons Filtered/OT:language=dflt;!

Compiling with LuaLaTeX or pdfLaTeX does not give any of these errors.

**Comment by ineshbose** [comment]
Is this related to #17? I hope this is resolved is v9.3.0 if you'd like to confirm

**Comment by hair-splitter** [comment]
This bug seems to be fixed in v9.4.0.

**Comment by Rimole** [comment]
When compiling  (with XeLaTeX) the document  given in my first post, I still get:

```
This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./Namenlos-1.tex
LaTeX2e <2023-06-01> patch level 1
L3 programming layer <2023-06-30>
(m:/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(m:/2023/texmf-dist/tex/latex/base/size10.clo)) (m:/2023/texmf-dist/tex/latex/simpleicons/simpleicons.sty
(m:/2023/texmf-dist/tex/generic/iftex/iftex.sty) (m:/2023/texmf-dist/tex/latex/fontspec/fontspec.sty
(m:/2023/texmf-dist/tex/latex/l3packages/xparse/xparse.sty (m:/2023/texmf-dist/tex/latex/l3kernel/expl3.sty
(m:/2023/texmf-dist/tex/latex/l3backend/l3backend-xetex.def))) (m:/2023/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(m:/2023/texmf-dist/tex/latex/base/fontenc.sty) (m:/2023/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
Missing character: There is no   (U+0020) in font [SimpleIcons.otf]/OT!
Missing character: There is no   (U+0020) in font [SimpleIcons.otf]/OT!
Missing character: There is no   (U+0020) in font [SimpleIcons.otf]/OT:language=dflt;!
(m:/2023/texmf-dist/tex/latex/simpleicons/simpleiconsglyphs-xeluatex.tex)) (./Namenlos-1.aux)
(m:/2023/texmf-dist/tex/latex/base/ts1cmr.fd) (./Namenlos-1.aux) )
No pages of output.
Transcript written on Namenlos-1.log.
```

**Comment by hair-splitter** [comment]
> This bug seems to be fixed in v9.4.0.

Sorry, I was wrong, Rimole's previous comment is correct!

**Comment by raffaem** [comment]
> > This bug seems to be fixed in v9.4.0.
> 
> Sorry, I was wrong, Rimole's previous comment is correct!

So we can close this?
